Error log

diff --git a/software/Makefile b/software/Makefile
--- a/software/Makefile
+++ b/software/Makefile
@@ -1,7 +1,7 @@
 # Arduino Makefile for Arduino Micro
 BOARD_TAG    = micro
 MONITOR_PORT = /dev/ttyACM0
-ARDUINO_LIBS = Wire MCP7940 OneWire DallasTemperature
+ARDUINO_LIBS = Wire MCP7940 OneWire DallasTemperature EEPROM
 
 # Arduino directory (adjust if needed)
 ARDUINO_DIR = /usr/share/arduino
@@ -10,17 +10,17 @@ ARDUINO_DIR = /usr/share/arduino
 TARGET = main
 SRC = src/$(TARGET).cc
 
+all: version tests $(TARGET_EEP) $(TARGET_HEX) upload monitor
 
 
 # Include Arduino.mk
 include /usr/share/arduino/Arduino.mk
-all: tests $(TARGET_EEP) $(TARGET_HEX)
 
 tests:
 	make -C test
 
 clean::
-	make -C test clean
+	make -C test clean ; rm -f version.h
 
 # Help target
 help:
@@ -31,7 +31,27 @@ help:
 	@echo "  clean   - Clean build files"
 
 monitor:
-	picocom -b 9600 --echo --imap lfcrlf  $(MONITOR_PORT)
+	@echo "Starting resilient serial monitor (C-a C-x to exit permanently)..."
+	@while true; do \
+		if [ -c $(MONITOR_PORT) ]; then \
+			echo "Device found, starting picocom..."; \
+			picocom -b 9600 --echo --imap lfcrlf $(MONITOR_PORT); \
+			exit_code=$$?; \
+			if [ $$exit_code -eq 0 ]; then \
+				echo "Picocom exited cleanly (C-a C-x). Stopping monitor."; \
+				break; \
+			else \
+				echo "Picocom exited with error (device disconnected?). Waiting..."; \
+				sleep 2; \
+			fi; \
+		else \
+			echo "Waiting for $(MONITOR_PORT) to appear..."; \
+			while [ ! -c $(MONITOR_PORT) ]; do sleep 1; done; \
+			echo "Device detected!"; \
+		fi; \
+	done
 
-
+PHONY: version
+version:
+	./generate_version.sh > version.h 2>/dev/null || echo "// Could not generate version from Git" > version.h
 .PHONY: help
